[package]
name = "kakarot_snippet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
alloy-consensus = "0.5"
reth-primitives = { git = "https://github.com/paradigmxyz/reth.git", tag = "v1.1.0" }
starknet = { git = "https://github.com/xJonathanLEI/starknet-rs" }
starknet_api = "0.11"
tokio = { version = "1.0", features = [ "full" ] }
